namespace SharpAstrology.Enums;
public enum IncarnationCrosses
{
    JuxtapositionCrossOfAlertness,
    JuxtapositionCrossOfAmbition,
    JuxtapositionCrossOfArticulation,
    JuxtapositionCrossOfAssimilation, 
    JuxtapositionCrossOfBargains,
    JuxtapositionCrossOfBeginnings,
    JuxtapositionCrossOfBehavior,
    JuxtapositionCrossOfCaring,
    JuxtapositionCrossOfCommitment,
    JuxtapositionCrossOfCompletion,
    JuxtapositionCrossOfConflict,
    JuxtapositionCrossOfConfusion,
    JuxtapositionCrossOfConservation,
    JuxtapositionCrossOfContribution,
    JuxtapositionCrossOfControl,
    JuxtapositionCrossOfCorrection,
    JuxtapositionCrossOfCrisis,
    JuxtapositionCrossOfDenial,
    JuxtapositionCrossOfDepth,
    JuxtapositionCrossOfDetail,
    JuxtapositionCrossOfDoubts,
    JuxtapositionCrossOfEmpowering,
    JuxtapositionCrossOfExperience,
    JuxtapositionCrossOfExperimentation,
    JuxtapositionCrossOfExtremes,
    JuxtapositionCrossOfFantasy,
    JuxtapositionCrossOfFates,
    JuxtapositionCrossOfFocus,
    JuxtapositionCrossOfFormulization,
    JuxtapositionCrossOfGrace,
    JuxtapositionCrossOfHabits,
    JuxtapositionCrossOfIdeas,
    JuxtapositionCrossOfInfluence,
    JuxtapositionCrossOfInnocence,
    JuxtapositionCrossOfInsight,
    JuxtapositionCrossOfInteraction,
    JuxtapositionCrossOfIntuition,
    JuxtapositionCrossOfLimitation,
    JuxtapositionCrossOfListening,
    JuxtapositionCrossOfMoods,
    JuxtapositionCrossOfMutation,
    JuxtapositionCrossOfNeed,
    JuxtapositionCrossOfOpinions,
    JuxtapositionCrossOfOpposition,
    JuxtapositionCrossOfOppression,
    JuxtapositionCrossOfPossession,
    JuxtapositionCrossOfPower,
    JuxtapositionCrossOfPrinciples,
    JuxtapositionCrossOfProvocation,
    JuxtapositionCrossOfRationalization,
    JuxtapositionCrossOfRetreat,
    JuxtapositionCrossOfRisks,
    JuxtapositionCrossOfSelfExpression,
    JuxtapositionCrossOfSerendipity,
    JuxtapositionCrossOfShock,
    JuxtapositionCrossOfStillness,
    JuxtapositionCrossOfStimulation,
    JuxtapositionCrossOfStrategy,
    JuxtapositionCrossOfTheDriver,
    JuxtapositionCrossOfTheNow,
    JuxtapositionCrossOfTheTrickster,
    JuxtapositionCrossOfThinking,
    JuxtapositionCrossOfValues,
    JuxtapositionCrossOfVitality,
    LeftAngleCrossOfAlignment2
}
public static class IncarnationCrossesesExtensionMethods
{
    public static (Gates, Gates, Gates, Gates) GetGeneKeys(this IncarnationCrosses cross) => cross switch
    {
        IncarnationCrosses.JuxtapositionCrossOfAlertness => (Gates.Key44, Gates.Key24, Gates.Key7, Gates.Key13),
                IncarnationCrosses.JuxtapositionCrossOfAmbition => (Gates.Key54, Gates.Key53, Gates.Key32,
                    Gates.Key42),
                IncarnationCrosses.JuxtapositionCrossOfArticulation => (Gates.Key12, Gates.Key11, Gates.Key25,
                    Gates.Key46),
                IncarnationCrosses.JuxtapositionCrossOfAssimilation => (Gates.Key23, Gates.Key43, Gates.Key30,
                    Gates.Key29),
                IncarnationCrosses.JuxtapositionCrossOfBargains => (Gates.Key37, Gates.Key40, Gates.Key5,
                    Gates.Key35),
                IncarnationCrosses.JuxtapositionCrossOfBeginnings => (Gates.Key53, Gates.Key54, Gates.Key42,
                    Gates.Key32),
                IncarnationCrosses.JuxtapositionCrossOfBehavior => (Gates.Key10, Gates.Key15, Gates.Key18,
                    Gates.Key17),
                IncarnationCrosses.JuxtapositionCrossOfCaring => (Gates.Key27, Gates.Key28, Gates.Key19,
                    Gates.Key33),
                IncarnationCrosses.JuxtapositionCrossOfCommitment => (Gates.Key29, Gates.Key30, Gates.Key20,
                    Gates.Key34),
                IncarnationCrosses.JuxtapositionCrossOfCompletion => (Gates.Key42, Gates.Key32, Gates.Key60,
                    Gates.Key56),
                IncarnationCrosses.JuxtapositionCrossOfConflict => (Gates.Key6, Gates.Key36, Gates.Key15,
                    Gates.Key10),
                IncarnationCrosses.JuxtapositionCrossOfConfusion => (Gates.Key64, Gates.Key63, Gates.Key45,
                    Gates.Key26),
                IncarnationCrosses.JuxtapositionCrossOfConservation => (Gates.Key32, Gates.Key42, Gates.Key56,
                    Gates.Key60),
                IncarnationCrosses.JuxtapositionCrossOfContribution => (Gates.Key8, Gates.Key14, Gates.Key55,
                    Gates.Key59),
                IncarnationCrosses.JuxtapositionCrossOfControl => (Gates.Key21, Gates.Key48, Gates.Key54,
                    Gates.Key53),
                IncarnationCrosses.JuxtapositionCrossOfCorrection => (Gates.Key18, Gates.Key17, Gates.Key39,
                    Gates.Key38),
                IncarnationCrosses.JuxtapositionCrossOfCrisis => (Gates.Key36, Gates.Key6, Gates.Key10,
                    Gates.Key15),
                IncarnationCrosses.JuxtapositionCrossOfDenial => (Gates.Key40, Gates.Key37, Gates.Key35,
                    Gates.Key5),
                IncarnationCrosses.JuxtapositionCrossOfDepth => (Gates.Key48, Gates.Key21, Gates.Key53,
                    Gates.Key54),
                IncarnationCrosses.JuxtapositionCrossOfDetail => (Gates.Key62, Gates.Key61, Gates.Key3,
                    Gates.Key50),
                IncarnationCrosses.JuxtapositionCrossOfDoubts => (Gates.Key63, Gates.Key64, Gates.Key26,
                    Gates.Key45),
                IncarnationCrosses.JuxtapositionCrossOfEmpowering => (Gates.Key14, Gates.Key8, Gates.Key59,
                    Gates.Key55),
                IncarnationCrosses.JuxtapositionCrossOfExperience => (Gates.Key35, Gates.Key5, Gates.Key22,
                    Gates.Key47),
                IncarnationCrosses.JuxtapositionCrossOfExperimentation => (Gates.Key16, Gates.Key9,
                    Gates.Key63, Gates.Key64),
                IncarnationCrosses.JuxtapositionCrossOfExtremes => (Gates.Key15, Gates.Key10, Gates.Key17, Gates.Key18),
                IncarnationCrosses.JuxtapositionCrossOfFantasy => (Gates.Key41, Gates.Key31, Gates.Key44, Gates.Key24),
                IncarnationCrosses.JuxtapositionCrossOfFates => (Gates.Key30, Gates.Key29, Gates.Key34, Gates.Key20),
                IncarnationCrosses.JuxtapositionCrossOfFocus => (Gates.Key9, Gates.Key16, Gates.Key64, Gates.Key63),
                IncarnationCrosses.JuxtapositionCrossOfFormulization => (Gates.Key4, Gates.Key49, Gates.Key8, Gates.Key14),
                IncarnationCrosses.JuxtapositionCrossOfGrace => (Gates.Key22, Gates.Key47, Gates.Key11, Gates.Key12),
                IncarnationCrosses.JuxtapositionCrossOfHabits => (Gates.Key5, Gates.Key35, Gates.Key47, Gates.Key22),
                IncarnationCrosses.JuxtapositionCrossOfIdeas => (Gates.Key11, Gates.Key12, Gates.Key46, Gates.Key25),
                IncarnationCrosses.JuxtapositionCrossOfInfluence => (Gates.Key31, Gates.Key41, Gates.Key24, Gates.Key44),
                IncarnationCrosses.JuxtapositionCrossOfInnocence => (Gates.Key25, Gates.Key46, Gates.Key58, Gates.Key52),
                IncarnationCrosses.JuxtapositionCrossOfInsight => (Gates.Key43, Gates.Key23, Gates.Key29, Gates.Key30),
                IncarnationCrosses.JuxtapositionCrossOfInteraction => (Gates.Key7, Gates.Key13, Gates.Key23, Gates.Key43),
                IncarnationCrosses.JuxtapositionCrossOfIntuition => (Gates.Key57, Gates.Key51, Gates.Key62, Gates.Key61),
                IncarnationCrosses.JuxtapositionCrossOfLimitation => (Gates.Key60, Gates.Key56, Gates.Key28, Gates.Key27),
                IncarnationCrosses.JuxtapositionCrossOfListening => (Gates.Key13, Gates.Key7, Gates.Key43, Gates.Key23),
                IncarnationCrosses.JuxtapositionCrossOfMoods => (Gates.Key55, Gates.Key59, Gates.Key9, Gates.Key16),
                IncarnationCrosses.JuxtapositionCrossOfMutation => (Gates.Key3, Gates.Key50, Gates.Key41, Gates.Key31),
                IncarnationCrosses.JuxtapositionCrossOfNeed => (Gates.Key19, Gates.Key33, Gates.Key1, Gates.Key2),
                IncarnationCrosses.JuxtapositionCrossOfOpinions => (Gates.Key17, Gates.Key18, Gates.Key38, Gates.Key39),
                IncarnationCrosses.JuxtapositionCrossOfOpposition => (Gates.Key38, Gates.Key39, Gates.Key57, Gates.Key51),
                IncarnationCrosses.JuxtapositionCrossOfOppression => (Gates.Key47, Gates.Key22, Gates.Key12, Gates.Key11),
                IncarnationCrosses.JuxtapositionCrossOfPossession => (Gates.Key45, Gates.Key26, Gates.Key36, Gates.Key6),
                IncarnationCrosses.JuxtapositionCrossOfPower => (Gates.Key34, Gates.Key20, Gates.Key40, Gates.Key37),
                IncarnationCrosses.JuxtapositionCrossOfPrinciples => (Gates.Key49, Gates.Key4, Gates.Key14, Gates.Key8),
                IncarnationCrosses.JuxtapositionCrossOfProvocation => (Gates.Key39, Gates.Key38, Gates.Key51, Gates.Key57),
                IncarnationCrosses.JuxtapositionCrossOfRationalization => (Gates.Key24, Gates.Key44, Gates.Key13, Gates.Key7),
                IncarnationCrosses.JuxtapositionCrossOfRetreat => (Gates.Key33, Gates.Key19, Gates.Key2, Gates.Key1),
                IncarnationCrosses.JuxtapositionCrossOfRisks => (Gates.Key28, Gates.Key27, Gates.Key33, Gates.Key19),
                IncarnationCrosses.JuxtapositionCrossOfSelfExpression => (Gates.Key1, Gates.Key2, Gates.Key4, Gates.Key49),
                IncarnationCrosses.JuxtapositionCrossOfSerendipity => (Gates.Key46, Gates.Key25, Gates.Key52, Gates.Key58),
                IncarnationCrosses.JuxtapositionCrossOfShock => (Gates.Key51, Gates.Key57, Gates.Key61, Gates.Key62),
                IncarnationCrosses.JuxtapositionCrossOfStillness => (Gates.Key52, Gates.Key58, Gates.Key21, Gates.Key48),
                IncarnationCrosses.JuxtapositionCrossOfStimulation => (Gates.Key56, Gates.Key60, Gates.Key27, Gates.Key28),
                IncarnationCrosses.JuxtapositionCrossOfStrategy => (Gates.Key59, Gates.Key55, Gates.Key16, Gates.Key9),
                IncarnationCrosses.JuxtapositionCrossOfTheDriver => (Gates.Key2, Gates.Key1, Gates.Key49, Gates.Key4),
                IncarnationCrosses.JuxtapositionCrossOfTheNow => (Gates.Key20, Gates.Key34, Gates.Key37, Gates.Key40),
                IncarnationCrosses.JuxtapositionCrossOfTheTrickster => (Gates.Key26, Gates.Key45, Gates.Key6, Gates.Key36),
                IncarnationCrosses.JuxtapositionCrossOfThinking => (Gates.Key61, Gates.Key62, Gates.Key50, Gates.Key3),
                IncarnationCrosses.JuxtapositionCrossOfValues => (Gates.Key50, Gates.Key3, Gates.Key31, Gates.Key41),
                IncarnationCrosses.JuxtapositionCrossOfVitality => (Gates.Key58, Gates.Key52, Gates.Key48, Gates.Key21),
            };

        public static IncarnationCrosses GetIncarnationCrosses(this (Gates, Gates, Gates, Gates) keys)
            => keys switch
            {
                (Gates.Key44, Gates.Key24, Gates.Key7, Gates.Key13) => IncarnationCrosses.JuxtapositionCrossOfAlertness,
                (Gates.Key54, Gates.Key53, Gates.Key32, Gates.Key42) => IncarnationCrosses.JuxtapositionCrossOfAmbition,
                (Gates.Key12, Gates.Key11, Gates.Key25, Gates.Key46) => IncarnationCrosses.JuxtapositionCrossOfArticulation,
                (Gates.Key23, Gates.Key43, Gates.Key30, Gates.Key29) => IncarnationCrosses.JuxtapositionCrossOfAssimilation,
                (Gates.Key37, Gates.Key40, Gates.Key5, Gates.Key35) => IncarnationCrosses.JuxtapositionCrossOfBargains,
                (Gates.Key53, Gates.Key54, Gates.Key42, Gates.Key32) => IncarnationCrosses.JuxtapositionCrossOfBeginnings,
                (Gates.Key10, Gates.Key15, Gates.Key18, Gates.Key17) => IncarnationCrosses.JuxtapositionCrossOfBehavior,
                (Gates.Key27, Gates.Key28, Gates.Key19, Gates.Key33) => IncarnationCrosses.JuxtapositionCrossOfCaring,
                (Gates.Key29, Gates.Key30, Gates.Key20, Gates.Key34) => IncarnationCrosses.JuxtapositionCrossOfCommitment,
                (Gates.Key42, Gates.Key32, Gates.Key60, Gates.Key56) => IncarnationCrosses.JuxtapositionCrossOfCompletion,
                (Gates.Key6, Gates.Key36, Gates.Key15, Gates.Key10) => IncarnationCrosses.JuxtapositionCrossOfConflict,
                (Gates.Key64, Gates.Key63, Gates.Key45, Gates.Key26) => IncarnationCrosses.JuxtapositionCrossOfConfusion,
                (Gates.Key32, Gates.Key42, Gates.Key56, Gates.Key60) => IncarnationCrosses.JuxtapositionCrossOfConservation,
                (Gates.Key8, Gates.Key14, Gates.Key55, Gates.Key59) => IncarnationCrosses.JuxtapositionCrossOfContribution,
                (Gates.Key21, Gates.Key48, Gates.Key54, Gates.Key53) => IncarnationCrosses.JuxtapositionCrossOfControl,
                (Gates.Key18, Gates.Key17, Gates.Key39, Gates.Key38) => IncarnationCrosses.JuxtapositionCrossOfCorrection,
                (Gates.Key36, Gates.Key6, Gates.Key10, Gates.Key15) => IncarnationCrosses.JuxtapositionCrossOfCrisis,
                (Gates.Key40, Gates.Key37, Gates.Key35, Gates.Key5) => IncarnationCrosses.JuxtapositionCrossOfDenial,
                (Gates.Key48, Gates.Key21, Gates.Key53, Gates.Key54) => IncarnationCrosses.JuxtapositionCrossOfDepth,
                (Gates.Key62, Gates.Key61, Gates.Key3, Gates.Key50) => IncarnationCrosses.JuxtapositionCrossOfDetail,
                (Gates.Key63, Gates.Key64, Gates.Key26, Gates.Key45) => IncarnationCrosses.JuxtapositionCrossOfDoubts,
                (Gates.Key14, Gates.Key8, Gates.Key59, Gates.Key55) => IncarnationCrosses.JuxtapositionCrossOfEmpowering,
                (Gates.Key35, Gates.Key5, Gates.Key22, Gates.Key47) => IncarnationCrosses.JuxtapositionCrossOfExperience,
                (Gates.Key16, Gates.Key9, Gates.Key63, Gates.Key64) => IncarnationCrosses.JuxtapositionCrossOfExperimentation,
                (Gates.Key15, Gates.Key10, Gates.Key17, Gates.Key18) => IncarnationCrosses.JuxtapositionCrossOfExtremes,
                (Gates.Key41, Gates.Key31, Gates.Key44, Gates.Key24) => IncarnationCrosses.JuxtapositionCrossOfFantasy,
                (Gates.Key30, Gates.Key29, Gates.Key34, Gates.Key20) => IncarnationCrosses.JuxtapositionCrossOfFates,
                (Gates.Key9, Gates.Key16, Gates.Key64, Gates.Key63) => IncarnationCrosses.JuxtapositionCrossOfFocus,
                (Gates.Key4, Gates.Key49, Gates.Key8, Gates.Key14) => IncarnationCrosses.JuxtapositionCrossOfFormulization,
                (Gates.Key22, Gates.Key47, Gates.Key11, Gates.Key12) => IncarnationCrosses.JuxtapositionCrossOfGrace,
                (Gates.Key5, Gates.Key35, Gates.Key47, Gates.Key22) => IncarnationCrosses.JuxtapositionCrossOfHabits,
                (Gates.Key11, Gates.Key12, Gates.Key46, Gates.Key25) => IncarnationCrosses.JuxtapositionCrossOfIdeas,
                (Gates.Key31, Gates.Key41, Gates.Key24, Gates.Key44) => IncarnationCrosses.JuxtapositionCrossOfInfluence,
                (Gates.Key25, Gates.Key46, Gates.Key58, Gates.Key52) => IncarnationCrosses.JuxtapositionCrossOfInnocence,
                (Gates.Key43, Gates.Key23, Gates.Key29, Gates.Key30) => IncarnationCrosses.JuxtapositionCrossOfInsight,
                (Gates.Key7, Gates.Key13, Gates.Key23, Gates.Key43) => IncarnationCrosses.JuxtapositionCrossOfInteraction,
                (Gates.Key57, Gates.Key51, Gates.Key62, Gates.Key61) => IncarnationCrosses.JuxtapositionCrossOfIntuition,
                (Gates.Key60, Gates.Key56, Gates.Key28, Gates.Key27) => IncarnationCrosses.JuxtapositionCrossOfLimitation,
                (Gates.Key13, Gates.Key7, Gates.Key43, Gates.Key23) => IncarnationCrosses.JuxtapositionCrossOfListening,
                (Gates.Key55, Gates.Key59, Gates.Key9, Gates.Key16) => IncarnationCrosses.JuxtapositionCrossOfMoods,
                (Gates.Key3, Gates.Key50, Gates.Key41, Gates.Key31) => IncarnationCrosses.JuxtapositionCrossOfMutation,
                (Gates.Key19, Gates.Key33, Gates.Key1, Gates.Key2) => IncarnationCrosses.JuxtapositionCrossOfNeed,
                (Gates.Key17, Gates.Key18, Gates.Key38, Gates.Key39) => IncarnationCrosses.JuxtapositionCrossOfOpinions,
                (Gates.Key38, Gates.Key39, Gates.Key57, Gates.Key51) => IncarnationCrosses.JuxtapositionCrossOfOpposition,
                (Gates.Key47, Gates.Key22, Gates.Key12, Gates.Key11) => IncarnationCrosses.JuxtapositionCrossOfOppression,
                (Gates.Key45, Gates.Key26, Gates.Key36, Gates.Key6) => IncarnationCrosses.JuxtapositionCrossOfPossession,
                (Gates.Key34, Gates.Key20, Gates.Key40, Gates.Key37) => IncarnationCrosses.JuxtapositionCrossOfPower,
                (Gates.Key49, Gates.Key4, Gates.Key14, Gates.Key8) => IncarnationCrosses.JuxtapositionCrossOfPrinciples,
                (Gates.Key39, Gates.Key38, Gates.Key51, Gates.Key57) => IncarnationCrosses.JuxtapositionCrossOfProvocation,
                (Gates.Key24, Gates.Key44, Gates.Key13, Gates.Key7) => IncarnationCrosses.JuxtapositionCrossOfRationalization,
                (Gates.Key33, Gates.Key19, Gates.Key2, Gates.Key1) => IncarnationCrosses.JuxtapositionCrossOfRetreat,
                (Gates.Key28, Gates.Key27, Gates.Key33, Gates.Key19) => IncarnationCrosses.JuxtapositionCrossOfRisks,
                (Gates.Key1, Gates.Key2, Gates.Key4, Gates.Key49) => IncarnationCrosses.JuxtapositionCrossOfSelfExpression,
                (Gates.Key46, Gates.Key25, Gates.Key52, Gates.Key58) => IncarnationCrosses.JuxtapositionCrossOfSerendipity,
                (Gates.Key51, Gates.Key57, Gates.Key61, Gates.Key62) => IncarnationCrosses.JuxtapositionCrossOfShock,
                (Gates.Key52, Gates.Key58, Gates.Key21, Gates.Key48) => IncarnationCrosses.JuxtapositionCrossOfStillness,
                (Gates.Key56, Gates.Key60, Gates.Key27, Gates.Key28) => IncarnationCrosses.JuxtapositionCrossOfStimulation,
                (Gates.Key59, Gates.Key55, Gates.Key16, Gates.Key9) => IncarnationCrosses.JuxtapositionCrossOfStrategy,
                (Gates.Key2, Gates.Key1, Gates.Key49, Gates.Key4) => IncarnationCrosses.JuxtapositionCrossOfTheDriver,
                (Gates.Key20, Gates.Key34, Gates.Key37, Gates.Key40) => IncarnationCrosses.JuxtapositionCrossOfTheNow,
                (Gates.Key26, Gates.Key45, Gates.Key6, Gates.Key36) => IncarnationCrosses.JuxtapositionCrossOfTheTrickster,
                (Gates.Key61, Gates.Key62, Gates.Key50, Gates.Key3) => IncarnationCrosses.JuxtapositionCrossOfThinking,
                (Gates.Key50, Gates.Key3, Gates.Key31, Gates.Key41) => IncarnationCrosses.JuxtapositionCrossOfValues,
                (Gates.Key58, Gates.Key52, Gates.Key48, Gates.Key21) => IncarnationCrosses.JuxtapositionCrossOfVitality,
            };
    }