#pragma warning disable CS8524

namespace SharpAstrology.Enums;
public enum IncarnationCrosses
{
    JuxtapositionCrossOfAlertness,
    JuxtapositionCrossOfAmbition,
    JuxtapositionCrossOfArticulation,
    JuxtapositionCrossOfAssimilation,
    JuxtapositionCrossOfBargains,
    JuxtapositionCrossOfBeginnings,
    JuxtapositionCrossOfBehavior,
    JuxtapositionCrossOfCaring,
    JuxtapositionCrossOfCommitment,
    JuxtapositionCrossOfCompletion,
    JuxtapositionCrossOfConflict,
    JuxtapositionCrossOfConfusion,
    JuxtapositionCrossOfConservation,
    JuxtapositionCrossOfContribution,
    JuxtapositionCrossOfControl,
    JuxtapositionCrossOfCorrection,
    JuxtapositionCrossOfCrisis,
    JuxtapositionCrossOfDenial,
    JuxtapositionCrossOfDepth,
    JuxtapositionCrossOfDetail,
    JuxtapositionCrossOfDoubts,
    JuxtapositionCrossOfEmpowering,
    JuxtapositionCrossOfExperience,
    JuxtapositionCrossOfExperimentation,
    JuxtapositionCrossOfExtremes,
    JuxtapositionCrossOfFantasy,
    JuxtapositionCrossOfFates,
    JuxtapositionCrossOfFocus,
    JuxtapositionCrossOfFormulization,
    JuxtapositionCrossOfGrace,
    JuxtapositionCrossOfHabits,
    JuxtapositionCrossOfIdeas,
    JuxtapositionCrossOfInfluence,
    JuxtapositionCrossOfInnocence,
    JuxtapositionCrossOfInsight,
    JuxtapositionCrossOfInteraction,
    JuxtapositionCrossOfIntuition,
    JuxtapositionCrossOfLimitation,
    JuxtapositionCrossOfListening,
    JuxtapositionCrossOfMoods,
    JuxtapositionCrossOfMutation,
    JuxtapositionCrossOfNeed,
    JuxtapositionCrossOfOpinions,
    JuxtapositionCrossOfOpposition,
    JuxtapositionCrossOfOppression,
    JuxtapositionCrossOfPossession,
    JuxtapositionCrossOfPower,
    JuxtapositionCrossOfPrinciples,
    JuxtapositionCrossOfProvocation,
    JuxtapositionCrossOfRationalization,
    JuxtapositionCrossOfRetreat,
    JuxtapositionCrossOfRisks,
    JuxtapositionCrossOfSelfExpression,
    JuxtapositionCrossOfSerendipity,
    JuxtapositionCrossOfShock,
    JuxtapositionCrossOfStillness,
    JuxtapositionCrossOfStimulation,
    JuxtapositionCrossOfStrategy,
    JuxtapositionCrossOfThinking,
    JuxtapositionCrossOfValues,
    JuxtapositionCrossOfVitality,
    JuxtapositionCrossOfTheDriver,
    JuxtapositionCrossOfTheNow,
    JuxtapositionCrossOfTheTrickster,
    LeftAngleCrossOfDuality2,
    LeftAngleCrossOfIndividualism,
    LeftAngleCrossOfIndividualism2,
    LeftAngleCrossOfLimitation2,
    LeftAngleCrossOfRefinement,
    LeftAngleCrossOfThePlane,
    LeftAngleCrossOfAlignment,
    LeftAngleCrossOfAlignment2,
    LeftAngleCrossOfConfrontation,
    LeftAngleCrossOfConfrontation2,
    LeftAngleCrossOfCycles,
    LeftAngleCrossOfCycles2,
    LeftAngleCrossOfDedication,
    LeftAngleCrossOfDedication2,
    LeftAngleCrossOfDefiance,
    LeftAngleCrossOfDefiance2,
    LeftAngleCrossOfDemands,
    LeftAngleCrossOfDemands2,
    LeftAngleCrossOfDistraction,
    LeftAngleCrossOfDistraction2,
    LeftAngleCrossOfDominion,
    LeftAngleCrossOfDominion2,
    LeftAngleCrossOfDuality,
    LeftAngleCrossOfEducation,
    LeftAngleCrossOfEducation2,
    LeftAngleCrossOfEndeavour,
    LeftAngleCrossOfEndeavour2,
    LeftAngleCrossOfHealing,
    LeftAngleCrossOfHealing2,
    LeftAngleCrossOfIdentification,
    LeftAngleCrossOfIdentification2,
    LeftAngleCrossOfIncarnation,
    LeftAngleCrossOfIncarnation2,
    LeftAngleCrossOfIndustry,
    LeftAngleCrossOfIndustry2,
    LeftAngleCrossOfInforming,
    LeftAngleCrossOfInforming2,
    LeftAngleCrossOfLimitation,
    LeftAngleCrossOfMasks,
    LeftAngleCrossOfMasks2,
    LeftAngleCrossOfMigration,
    LeftAngleCrossOfMigration2,
    LeftAngleCrossOfObscuration,
    LeftAngleCrossOfObscuration2,
    LeftAngleCrossOfPrevention,
    LeftAngleCrossOfPrevention2,
    LeftAngleCrossOfRefinement2,
    LeftAngleCrossOfRevolution,
    LeftAngleCrossOfRevolution2,
    LeftAngleCrossOfSeparation,
    LeftAngleCrossOfSeparation2,
    LeftAngleCrossOfSpirit,
    LeftAngleCrossOfSpirit2,
    LeftAngleCrossOfUncertainty,
    LeftAngleCrossOfUncertainty2,
    LeftAngleCrossOfUpheaval,
    LeftAngleCrossOfUpheaval2,
    LeftAngleCrossOfWishes,
    LeftAngleCrossOfWishes2,
    LeftAngleCrossOfTheAlpha,
    LeftAngleCrossOfTheAlpha2,
    LeftAngleCrossOfTheClarion,
    LeftAngleCrossOfTheClarion2,
    LeftAngleCrossOfThePlane2,
    RightAngleCrossOfConsciousness,
    RightAngleCrossOfConsciousness2,
    RightAngleCrossOfConsciousness3,
    RightAngleCrossOfConsciousness4,
    RightAngleCrossOfContagion,
    RightAngleCrossOfContagion2,
    RightAngleCrossOfContagion3,
    RightAngleCrossOfContagion4,
    RightAngleCrossOfEden2,
    RightAngleCrossOfEden3,
    RightAngleCrossOfEden4,
    RightAngleCrossOfExplanation,
    RightAngleCrossOfExplanation2,
    RightAngleCrossOfExplanation3,
    RightAngleCrossOfExplanation4,
    RightAngleCrossOfLaws,
    RightAngleCrossOfLaws2,
    RightAngleCrossOfLaws3,
    RightAngleCrossOfLaws4,
    RightAngleCrossOfMaya,
    RightAngleCrossOfMaya2,
    RightAngleCrossOfMaya3,
    RightAngleCrossOfMaya4,
    RightAngleCrossOfPenetration,
    RightAngleCrossOfPenetration2,
    RightAngleCrossOfPenetration3,
    RightAngleCrossOfPenetration4,
    RightAngleCrossOfPlanning,
    RightAngleCrossOfPlanning2,
    RightAngleCrossOfPlanning3,
    RightAngleCrossOfPlanning4,
    RightAngleCrossOfRulership,
    RightAngleCrossOfRulership2,
    RightAngleCrossOfRulership3,
    RightAngleCrossOfRulership4,
    RightAngleCrossOfService,
    RightAngleCrossOfService2,
    RightAngleCrossOfService3,
    RightAngleCrossOfService4,
    RightAngleCrossOfTension,
    RightAngleCrossOfTension2,
    RightAngleCrossOfTension3,
    RightAngleCrossOfTension4,
    RightAngleCrossOfVesselOfLove4,
    RightAngleCrossOfTheEden,
    RightAngleCrossOfTheFourWays,
    RightAngleCrossOfTheFourWays2,
    RightAngleCrossOfTheFourWays3,
    RightAngleCrossOfTheFourWays4,
    RightAngleCrossOfTheSleepingPhoenix,
    RightAngleCrossOfTheSleepingPhoenix2,
    RightAngleCrossOfTheSleepingPhoenix3,
    RightAngleCrossOfTheSleepingPhoenix4,
    RightAngleCrossOfTheSphinx,
    RightAngleCrossOfTheSphinx2,
    RightAngleCrossOfTheSphinx3,
    RightAngleCrossOfTheSphinx4,
    RightAngleCrossOfTheUnexpected,
    RightAngleCrossOfTheUnexpected2,
    RightAngleCrossOfTheUnexpected3,
    RightAngleCrossOfTheUnexpected4,
    RightAngleCrossOfTheVesselOfLove,
    RightAngleCrossOfTheVesselOfLove2,
    RightAngleCrossOfTheVesselOfLove3
}
public static class IncarnationCrossesExtensionMethods
{
    public static (Gates, Angles) ToGeneKeys(this IncarnationCrosses cross) => cross switch
    {
        IncarnationCrosses.JuxtapositionCrossOfAlertness => (Gates.Key44, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfAmbition => (Gates.Key54, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfArticulation => (Gates.Key12, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfAssimilation => (Gates.Key23, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfBargains => (Gates.Key37, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfBeginnings => (Gates.Key53, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfBehavior => (Gates.Key10, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCaring => (Gates.Key27, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCommitment => (Gates.Key29, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCompletion => (Gates.Key42, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfConflict => (Gates.Key6, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfConfusion => (Gates.Key64, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfConservation => (Gates.Key32, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfContribution => (Gates.Key8, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfControl => (Gates.Key21, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCorrection => (Gates.Key18, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCrisis => (Gates.Key36, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDenial => (Gates.Key40, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDepth => (Gates.Key48, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDetail => (Gates.Key62, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDoubts => (Gates.Key63, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfEmpowering => (Gates.Key14, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfExperience => (Gates.Key35, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfExperimentation => (Gates.Key16, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfExtremes => (Gates.Key15, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFantasy => (Gates.Key41, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFates => (Gates.Key30, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFocus => (Gates.Key9, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFormulization => (Gates.Key4, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfGrace => (Gates.Key22, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfHabits => (Gates.Key5, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfIdeas => (Gates.Key11, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInfluence => (Gates.Key31, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInnocence => (Gates.Key25, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInsight => (Gates.Key43, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInteraction => (Gates.Key7, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfIntuition => (Gates.Key57, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfLimitation => (Gates.Key60, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfListening => (Gates.Key13, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfMoods => (Gates.Key55, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfMutation => (Gates.Key3, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfNeed => (Gates.Key19, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfOpinions => (Gates.Key17, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfOpposition => (Gates.Key38, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfOppression => (Gates.Key47, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfPossession => (Gates.Key45, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfPower => (Gates.Key34, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfPrinciples => (Gates.Key49, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfProvocation => (Gates.Key39, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfRationalization => (Gates.Key24, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfRetreat => (Gates.Key33, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfRisks => (Gates.Key28, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfSelfExpression => (Gates.Key1, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfSerendipity => (Gates.Key46, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfShock => (Gates.Key51, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfStillness => (Gates.Key52, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfStimulation => (Gates.Key56, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfStrategy => (Gates.Key59, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfThinking => (Gates.Key61, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfValues => (Gates.Key50, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfVitality => (Gates.Key58, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfTheDriver => (Gates.Key2, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfTheNow => (Gates.Key20, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfTheTrickster => (Gates.Key26, Angles.Juxtaposition),
        IncarnationCrosses.LeftAngleCrossOfDuality2 => (Gates.Key34, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndividualism => (Gates.Key39, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndividualism2 => (Gates.Key38, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfLimitation2 => (Gates.Key32, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRefinement => (Gates.Key33, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfThePlane => (Gates.Key36, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfAlignment => (Gates.Key27, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfAlignment2 => (Gates.Key28, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfConfrontation => (Gates.Key45, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfConfrontation2 => (Gates.Key26, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfCycles => (Gates.Key53, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfCycles2 => (Gates.Key54, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDedication => (Gates.Key23, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDedication2 => (Gates.Key43, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDefiance => (Gates.Key2, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDefiance2 => (Gates.Key1, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDemands => (Gates.Key52, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDemands2 => (Gates.Key58, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDistraction => (Gates.Key56, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDistraction2 => (Gates.Key60, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDominion => (Gates.Key63, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDominion2 => (Gates.Key64, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDuality => (Gates.Key20, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEducation => (Gates.Key12, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEducation2 => (Gates.Key11, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEndeavour => (Gates.Key21, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEndeavour2 => (Gates.Key48, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfHealing => (Gates.Key25, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfHealing2 => (Gates.Key46, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIdentification => (Gates.Key16, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIdentification2 => (Gates.Key9, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIncarnation => (Gates.Key24, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIncarnation2 => (Gates.Key44, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndustry => (Gates.Key30, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndustry2 => (Gates.Key29, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfInforming => (Gates.Key22, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfInforming2 => (Gates.Key47, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfLimitation => (Gates.Key42, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMasks => (Gates.Key13, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMasks2 => (Gates.Key7, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMigration => (Gates.Key37, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMigration2 => (Gates.Key40, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfObscuration => (Gates.Key62, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfObscuration2 => (Gates.Key61, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfPrevention => (Gates.Key15, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfPrevention2 => (Gates.Key10, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRefinement2 => (Gates.Key19, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRevolution => (Gates.Key49, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRevolution2 => (Gates.Key4, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSeparation => (Gates.Key35, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSeparation2 => (Gates.Key5, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSpirit => (Gates.Key55, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSpirit2 => (Gates.Key59, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUncertainty => (Gates.Key8, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUncertainty2 => (Gates.Key14, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUpheaval => (Gates.Key17, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUpheaval2 => (Gates.Key18, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfWishes => (Gates.Key3, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfWishes2 => (Gates.Key50, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheAlpha => (Gates.Key31, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheAlpha2 => (Gates.Key41, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheClarion => (Gates.Key51, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheClarion2 => (Gates.Key57, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfThePlane2 => (Gates.Key6, Angles.Left),
        IncarnationCrosses.RightAngleCrossOfConsciousness => (Gates.Key63, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfConsciousness2 => (Gates.Key35, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfConsciousness3 => (Gates.Key64, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfConsciousness4 => (Gates.Key5, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion => (Gates.Key30, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion2 => (Gates.Key8, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion3 => (Gates.Key29, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion4 => (Gates.Key14, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfEden2 => (Gates.Key12, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfEden3 => (Gates.Key6, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfEden4 => (Gates.Key11, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation => (Gates.Key49, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation2 => (Gates.Key23, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation3 => (Gates.Key4, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation4 => (Gates.Key43, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws => (Gates.Key3, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws2 => (Gates.Key56, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws3 => (Gates.Key50, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws4 => (Gates.Key60, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya => (Gates.Key42, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya2 => (Gates.Key62, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya3 => (Gates.Key32, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya4 => (Gates.Key61, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration => (Gates.Key51, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration2 => (Gates.Key53, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration3 => (Gates.Key57, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration4 => (Gates.Key54, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning => (Gates.Key37, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning2 => (Gates.Key16, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning3 => (Gates.Key40, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning4 => (Gates.Key9, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership => (Gates.Key22, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership2 => (Gates.Key45, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership3 => (Gates.Key47, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership4 => (Gates.Key26, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService => (Gates.Key17, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService2 => (Gates.Key52, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService3 => (Gates.Key18, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService4 => (Gates.Key58, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension => (Gates.Key21, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension2 => (Gates.Key39, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension3 => (Gates.Key48, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension4 => (Gates.Key38, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfVesselOfLove4 => (Gates.Key10, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheEden => (Gates.Key36, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays => (Gates.Key24, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays2 => (Gates.Key33, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays3 => (Gates.Key44, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays4 => (Gates.Key19, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix => (Gates.Key55, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix2 => (Gates.Key20, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix3 => (Gates.Key59, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix4 => (Gates.Key34, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx => (Gates.Key13, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx2 => (Gates.Key2, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx3 => (Gates.Key7, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx4 => (Gates.Key1, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected => (Gates.Key27, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected2 => (Gates.Key31, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected3 => (Gates.Key28, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected4 => (Gates.Key41, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheVesselOfLove => (Gates.Key25, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheVesselOfLove2 => (Gates.Key15, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheVesselOfLove3 => (Gates.Key46, Angles.Right)
    };

        public static IncarnationCrosses ToIncarnationCross(this (Gates, Angles) position) => position switch
            {
                (Gates.Key44, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfAlertness,
                (Gates.Key54, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfAmbition,
                (Gates.Key12, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfArticulation,
                (Gates.Key23, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfAssimilation,
                (Gates.Key37, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfBargains,
                (Gates.Key53, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfBeginnings,
                (Gates.Key10, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfBehavior,
                (Gates.Key27, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCaring,
                (Gates.Key29, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCommitment,
                (Gates.Key42, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCompletion,
                (Gates.Key6, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfConflict,
                (Gates.Key64, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfConfusion,
                (Gates.Key32, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfConservation,
                (Gates.Key8, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfContribution,
                (Gates.Key21, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfControl,
                (Gates.Key18, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCorrection,
                (Gates.Key36, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCrisis,
                (Gates.Key40, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDenial,
                (Gates.Key48, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDepth,
                (Gates.Key62, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDetail,
                (Gates.Key63, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDoubts,
                (Gates.Key14, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfEmpowering,
                (Gates.Key35, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfExperience,
                (Gates.Key16, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfExperimentation,
                (Gates.Key15, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfExtremes,
                (Gates.Key41, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFantasy,
                (Gates.Key30, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFates,
                (Gates.Key9, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFocus,
                (Gates.Key4, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFormulization,
                (Gates.Key22, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfGrace,
                (Gates.Key5, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfHabits,
                (Gates.Key11, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfIdeas,
                (Gates.Key31, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInfluence,
                (Gates.Key25, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInnocence,
                (Gates.Key43, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInsight,
                (Gates.Key7, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInteraction,
                (Gates.Key57, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfIntuition,
                (Gates.Key60, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfLimitation,
                (Gates.Key13, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfListening,
                (Gates.Key55, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfMoods,
                (Gates.Key3, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfMutation,
                (Gates.Key19, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfNeed,
                (Gates.Key17, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfOpinions,
                (Gates.Key38, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfOpposition,
                (Gates.Key47, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfOppression,
                (Gates.Key45, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfPossession,
                (Gates.Key34, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfPower,
                (Gates.Key49, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfPrinciples,
                (Gates.Key39, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfProvocation,
                (Gates.Key24, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfRationalization,
                (Gates.Key33, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfRetreat,
                (Gates.Key28, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfRisks,
                (Gates.Key1, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfSelfExpression,
                (Gates.Key46, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfSerendipity,
                (Gates.Key51, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfShock,
                (Gates.Key52, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfStillness,
                (Gates.Key56, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfStimulation,
                (Gates.Key59, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfStrategy,
                (Gates.Key61, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfThinking,
                (Gates.Key50, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfValues,
                (Gates.Key58, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfVitality,
                (Gates.Key2, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfTheDriver,
                (Gates.Key20, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfTheNow,
                (Gates.Key26, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfTheTrickster,
                (Gates.Key34, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDuality2,
                (Gates.Key39, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndividualism,
                (Gates.Key38, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndividualism2,
                (Gates.Key32, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfLimitation2,
                (Gates.Key33, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRefinement,
                (Gates.Key36, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfThePlane,
                (Gates.Key27, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfAlignment,
                (Gates.Key28, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfAlignment2,
                (Gates.Key45, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfConfrontation,
                (Gates.Key26, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfConfrontation2,
                (Gates.Key53, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfCycles,
                (Gates.Key54, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfCycles2,
                (Gates.Key23, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDedication,
                (Gates.Key43, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDedication2,
                (Gates.Key2, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDefiance,
                (Gates.Key1, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDefiance2,
                (Gates.Key52, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDemands,
                (Gates.Key58, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDemands2,
                (Gates.Key56, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDistraction,
                (Gates.Key60, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDistraction2,
                (Gates.Key63, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDominion,
                (Gates.Key64, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDominion2,
                (Gates.Key20, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDuality,
                (Gates.Key12, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEducation,
                (Gates.Key11, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEducation2,
                (Gates.Key21, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEndeavour,
                (Gates.Key48, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEndeavour2,
                (Gates.Key25, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfHealing,
                (Gates.Key46, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfHealing2,
                (Gates.Key16, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIdentification,
                (Gates.Key9, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIdentification2,
                (Gates.Key24, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIncarnation,
                (Gates.Key44, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIncarnation2,
                (Gates.Key30, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndustry,
                (Gates.Key29, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndustry2,
                (Gates.Key22, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfInforming,
                (Gates.Key47, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfInforming2,
                (Gates.Key42, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfLimitation,
                (Gates.Key13, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMasks,
                (Gates.Key7, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMasks2,
                (Gates.Key37, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMigration,
                (Gates.Key40, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMigration2,
                (Gates.Key62, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfObscuration,
                (Gates.Key61, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfObscuration2,
                (Gates.Key15, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfPrevention,
                (Gates.Key10, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfPrevention2,
                (Gates.Key19, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRefinement2,
                (Gates.Key49, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRevolution,
                (Gates.Key4, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRevolution2,
                (Gates.Key35, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSeparation,
                (Gates.Key5, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSeparation2,
                (Gates.Key55, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSpirit,
                (Gates.Key59, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSpirit2,
                (Gates.Key8, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUncertainty,
                (Gates.Key14, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUncertainty2,
                (Gates.Key17, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUpheaval,
                (Gates.Key18, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUpheaval2,
                (Gates.Key3, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfWishes,
                (Gates.Key50, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfWishes2,
                (Gates.Key31, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheAlpha,
                (Gates.Key41, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheAlpha2,
                (Gates.Key51, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheClarion,
                (Gates.Key57, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheClarion2,
                (Gates.Key6, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfThePlane2,
                (Gates.Key63, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness,
                (Gates.Key35, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness2,
                (Gates.Key64, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness3,
                (Gates.Key5, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness4,
                (Gates.Key30, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion,
                (Gates.Key8, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion2,
                (Gates.Key29, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion3,
                (Gates.Key14, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion4,
                (Gates.Key12, Angles.Right) => IncarnationCrosses.RightAngleCrossOfEden2,
                (Gates.Key6, Angles.Right) => IncarnationCrosses.RightAngleCrossOfEden3,
                (Gates.Key11, Angles.Right) => IncarnationCrosses.RightAngleCrossOfEden4,
                (Gates.Key49, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation,
                (Gates.Key23, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation2,
                (Gates.Key4, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation3,
                (Gates.Key43, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation4,
                (Gates.Key3, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws,
                (Gates.Key56, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws2,
                (Gates.Key50, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws3,
                (Gates.Key60, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws4,
                (Gates.Key42, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya,
                (Gates.Key62, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya2,
                (Gates.Key32, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya3,
                (Gates.Key61, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya4,
                (Gates.Key51, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration,
                (Gates.Key53, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration2,
                (Gates.Key57, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration3,
                (Gates.Key54, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration4,
                (Gates.Key37, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning,
                (Gates.Key16, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning2,
                (Gates.Key40, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning3,
                (Gates.Key9, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning4,
                (Gates.Key22, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership,
                (Gates.Key45, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership2,
                (Gates.Key47, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership3,
                (Gates.Key26, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership4,
                (Gates.Key17, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService,
                (Gates.Key52, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService2,
                (Gates.Key18, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService3,
                (Gates.Key58, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService4,
                (Gates.Key21, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension,
                (Gates.Key39, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension2,
                (Gates.Key48, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension3,
                (Gates.Key38, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension4,
                (Gates.Key10, Angles.Right) => IncarnationCrosses.RightAngleCrossOfVesselOfLove4,
                (Gates.Key36, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheEden,
                (Gates.Key24, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays,
                (Gates.Key33, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays2,
                (Gates.Key44, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays3,
                (Gates.Key19, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays4,
                (Gates.Key55, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix,
                (Gates.Key20, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix2,
                (Gates.Key59, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix3,
                (Gates.Key34, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix4,
                (Gates.Key13, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx,
                (Gates.Key2, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx2,
                (Gates.Key7, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx3,
                (Gates.Key1, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx4,
                (Gates.Key27, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected,
                (Gates.Key31, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected2,
                (Gates.Key28, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected3,
                (Gates.Key41, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected4,
                (Gates.Key25, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheVesselOfLove,
                (Gates.Key15, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheVesselOfLove2,
                (Gates.Key46, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheVesselOfLove3
            };

            public static string ToText(this IncarnationCrosses cross) => cross switch
            {
                IncarnationCrosses.JuxtapositionCrossOfAlertness => "The Juxtaposition Cross of Alertness",
                IncarnationCrosses.JuxtapositionCrossOfAmbition => "The Juxtaposition Cross of Ambition",
                IncarnationCrosses.JuxtapositionCrossOfArticulation => "The Juxtaposition Cross of Articulation",
                IncarnationCrosses.JuxtapositionCrossOfAssimilation => "The Juxtaposition Cross of Assimilation",
                IncarnationCrosses.JuxtapositionCrossOfBargains => "The Juxtaposition Cross of Bargains",
                IncarnationCrosses.JuxtapositionCrossOfBeginnings => "The Juxtaposition Cross of Beginnings",
                IncarnationCrosses.JuxtapositionCrossOfBehavior => "The Juxtaposition Cross of Behavior",
                IncarnationCrosses.JuxtapositionCrossOfCaring => "The Juxtaposition Cross of Caring",
                IncarnationCrosses.JuxtapositionCrossOfCommitment => "The Juxtaposition Cross of Commitment",
                IncarnationCrosses.JuxtapositionCrossOfCompletion => "The Juxtaposition Cross of Completion",
                IncarnationCrosses.JuxtapositionCrossOfConflict => "The Juxtaposition Cross of Conflict",
                IncarnationCrosses.JuxtapositionCrossOfConfusion => "The Juxtaposition Cross of Confusion",
                IncarnationCrosses.JuxtapositionCrossOfConservation => "The Juxtaposition Cross of Conservation",
                IncarnationCrosses.JuxtapositionCrossOfContribution => "The Juxtaposition Cross of Contribution",
                IncarnationCrosses.JuxtapositionCrossOfControl => "The Juxtaposition Cross of Control",
                IncarnationCrosses.JuxtapositionCrossOfCorrection => "The Juxtaposition Cross of Correction",
                IncarnationCrosses.JuxtapositionCrossOfCrisis => "The Juxtaposition Cross of Crisis",
                IncarnationCrosses.JuxtapositionCrossOfDenial => "The Juxtaposition Cross of Denial",
                IncarnationCrosses.JuxtapositionCrossOfDepth => "The Juxtaposition Cross of Depth",
                IncarnationCrosses.JuxtapositionCrossOfDetail => "The Juxtaposition Cross of Detail",
                IncarnationCrosses.JuxtapositionCrossOfDoubts => "The Juxtaposition Cross of Doubts",
                IncarnationCrosses.JuxtapositionCrossOfEmpowering => "The Juxtaposition Cross of Empowering",
                IncarnationCrosses.JuxtapositionCrossOfExperience => "The Juxtaposition Cross of Experience",
                IncarnationCrosses.JuxtapositionCrossOfExperimentation => "The Juxtaposition Cross of Experimentation",
                IncarnationCrosses.JuxtapositionCrossOfExtremes => "The Juxtaposition Cross of Extremes",
                IncarnationCrosses.JuxtapositionCrossOfFantasy => "The Juxtaposition Cross of Fantasy",
                IncarnationCrosses.JuxtapositionCrossOfFates => "The Juxtaposition Cross of Fates",
                IncarnationCrosses.JuxtapositionCrossOfFocus => "The Juxtaposition Cross of Focus",
                IncarnationCrosses.JuxtapositionCrossOfFormulization => "The Juxtaposition Cross of Formulization",
                IncarnationCrosses.JuxtapositionCrossOfGrace => "The Juxtaposition Cross of Grace",
                IncarnationCrosses.JuxtapositionCrossOfHabits => "The Juxtaposition Cross of Habits",
                IncarnationCrosses.JuxtapositionCrossOfIdeas => "The Juxtaposition Cross of Ideas",
                IncarnationCrosses.JuxtapositionCrossOfInfluence => "The Juxtaposition Cross of Influence",
                IncarnationCrosses.JuxtapositionCrossOfInnocence => "The Juxtaposition Cross of Innocence",
                IncarnationCrosses.JuxtapositionCrossOfInsight => "The Juxtaposition Cross of Insight",
                IncarnationCrosses.JuxtapositionCrossOfInteraction => "The Juxtaposition Cross of Interaction",
                IncarnationCrosses.JuxtapositionCrossOfIntuition => "The Juxtaposition Cross of Intuition",
                IncarnationCrosses.JuxtapositionCrossOfLimitation => "The Juxtaposition Cross of Limitation",
                IncarnationCrosses.JuxtapositionCrossOfListening => "The Juxtaposition Cross of Listening",
                IncarnationCrosses.JuxtapositionCrossOfMoods => "The Juxtaposition Cross of Moods",
                IncarnationCrosses.JuxtapositionCrossOfMutation => "The Juxtaposition Cross of Mutation",
                IncarnationCrosses.JuxtapositionCrossOfNeed => "The Juxtaposition Cross of Need",
                IncarnationCrosses.JuxtapositionCrossOfOpinions => "The Juxtaposition Cross of Opinions",
                IncarnationCrosses.JuxtapositionCrossOfOpposition => "The Juxtaposition Cross of Opposition",
                IncarnationCrosses.JuxtapositionCrossOfOppression => "The Juxtaposition Cross of Oppression",
                IncarnationCrosses.JuxtapositionCrossOfPossession => "The Juxtaposition Cross of Possession",
                IncarnationCrosses.JuxtapositionCrossOfPower => "The Juxtaposition Cross of Power",
                IncarnationCrosses.JuxtapositionCrossOfPrinciples => "The Juxtaposition Cross of Principles",
                IncarnationCrosses.JuxtapositionCrossOfProvocation => "The Juxtaposition Cross of Provocation",
                IncarnationCrosses.JuxtapositionCrossOfRationalization => "The Juxtaposition Cross of Rationalization",
                IncarnationCrosses.JuxtapositionCrossOfRetreat => "The Juxtaposition Cross of Retreat",
                IncarnationCrosses.JuxtapositionCrossOfRisks => "The Juxtaposition Cross of Risks",
                IncarnationCrosses.JuxtapositionCrossOfSelfExpression => "The Juxtaposition Cross of Self-Expression",
                IncarnationCrosses.JuxtapositionCrossOfSerendipity => "The Juxtaposition Cross of Serendipity",
                IncarnationCrosses.JuxtapositionCrossOfShock => "The Juxtaposition Cross of Shock",
                IncarnationCrosses.JuxtapositionCrossOfStillness => "The Juxtaposition Cross of Stillness",
                IncarnationCrosses.JuxtapositionCrossOfStimulation => "The Juxtaposition Cross of Stimulation",
                IncarnationCrosses.JuxtapositionCrossOfStrategy => "The Juxtaposition Cross of Strategy",
                IncarnationCrosses.JuxtapositionCrossOfThinking => "The Juxtaposition Cross of Thinking",
                IncarnationCrosses.JuxtapositionCrossOfValues => "The Juxtaposition Cross of Values",
                IncarnationCrosses.JuxtapositionCrossOfVitality => "The Juxtaposition Cross of Vitality",
                IncarnationCrosses.JuxtapositionCrossOfTheDriver => "The Juxtaposition Cross of the Driver",
                IncarnationCrosses.JuxtapositionCrossOfTheNow => "The Juxtaposition Cross of the Now",
                IncarnationCrosses.JuxtapositionCrossOfTheTrickster => "The Juxtaposition Cross of the Trickster",
                IncarnationCrosses.LeftAngleCrossOfDuality2 => "The Left Angle Cross of  Duality 2",
                IncarnationCrosses.LeftAngleCrossOfIndividualism => "The Left Angle Cross of  Individualism",
                IncarnationCrosses.LeftAngleCrossOfIndividualism2 => "The Left Angle Cross of  Individualism 2",
                IncarnationCrosses.LeftAngleCrossOfLimitation2 => "The Left Angle Cross of  Limitation 2",
                IncarnationCrosses.LeftAngleCrossOfRefinement => "The Left Angle Cross of  Refinement",
                IncarnationCrosses.LeftAngleCrossOfThePlane => "The Left Angle Cross of  the Plane",
                IncarnationCrosses.LeftAngleCrossOfAlignment => "The Left Angle Cross of Alignment",
                IncarnationCrosses.LeftAngleCrossOfAlignment2 => "The Left Angle Cross of Alignment 2",
                IncarnationCrosses.LeftAngleCrossOfConfrontation => "The Left Angle Cross of Confrontation",
                IncarnationCrosses.LeftAngleCrossOfConfrontation2 => "The Left Angle Cross of Confrontation 2",
                IncarnationCrosses.LeftAngleCrossOfCycles => "The Left Angle Cross of Cycles",
                IncarnationCrosses.LeftAngleCrossOfCycles2 => "The Left Angle Cross of Cycles 2",
                IncarnationCrosses.LeftAngleCrossOfDedication => "The Left Angle Cross of Dedication",
                IncarnationCrosses.LeftAngleCrossOfDedication2 => "The Left Angle Cross of Dedication 2",
                IncarnationCrosses.LeftAngleCrossOfDefiance => "The Left Angle Cross of Defiance",
                IncarnationCrosses.LeftAngleCrossOfDefiance2 => "The Left Angle Cross of Defiance 2",
                IncarnationCrosses.LeftAngleCrossOfDemands => "The Left Angle Cross of Demands",
                IncarnationCrosses.LeftAngleCrossOfDemands2 => "The Left Angle Cross of Demands 2",
                IncarnationCrosses.LeftAngleCrossOfDistraction => "The Left Angle Cross of Distraction",
                IncarnationCrosses.LeftAngleCrossOfDistraction2 => "The Left Angle Cross of Distraction 2",
                IncarnationCrosses.LeftAngleCrossOfDominion => "The Left Angle Cross of Dominion",
                IncarnationCrosses.LeftAngleCrossOfDominion2 => "The Left Angle Cross of Dominion 2",
                IncarnationCrosses.LeftAngleCrossOfDuality => "The Left Angle Cross of Duality",
                IncarnationCrosses.LeftAngleCrossOfEducation => "The Left Angle Cross of Education",
                IncarnationCrosses.LeftAngleCrossOfEducation2 => "The Left Angle Cross of Education 2",
                IncarnationCrosses.LeftAngleCrossOfEndeavour => "The Left Angle Cross of Endeavour",
                IncarnationCrosses.LeftAngleCrossOfEndeavour2 => "The Left Angle Cross of Endeavour 2",
                IncarnationCrosses.LeftAngleCrossOfHealing => "The Left Angle Cross of Healing",
                IncarnationCrosses.LeftAngleCrossOfHealing2 => "The Left Angle Cross of Healing 2",
                IncarnationCrosses.LeftAngleCrossOfIdentification => "The Left Angle Cross of Identification",
                IncarnationCrosses.LeftAngleCrossOfIdentification2 => "The Left Angle Cross of Identification 2",
                IncarnationCrosses.LeftAngleCrossOfIncarnation => "The Left Angle Cross of Incarnation",
                IncarnationCrosses.LeftAngleCrossOfIncarnation2 => "The Left Angle Cross of Incarnation 2",
                IncarnationCrosses.LeftAngleCrossOfIndustry => "The Left Angle Cross of Industry",
                IncarnationCrosses.LeftAngleCrossOfIndustry2 => "The Left Angle Cross of Industry 2",
                IncarnationCrosses.LeftAngleCrossOfInforming => "The Left Angle Cross of Informing",
                IncarnationCrosses.LeftAngleCrossOfInforming2 => "The Left Angle Cross of Informing 2",
                IncarnationCrosses.LeftAngleCrossOfLimitation => "The Left Angle Cross of Limitation",
                IncarnationCrosses.LeftAngleCrossOfMasks => "The Left Angle Cross of Masks",
                IncarnationCrosses.LeftAngleCrossOfMasks2 => "The Left Angle Cross of Masks 2",
                IncarnationCrosses.LeftAngleCrossOfMigration => "The Left Angle Cross of Migration",
                IncarnationCrosses.LeftAngleCrossOfMigration2 => "The Left Angle Cross of Migration 2",
                IncarnationCrosses.LeftAngleCrossOfObscuration => "The Left Angle Cross of Obscuration",
                IncarnationCrosses.LeftAngleCrossOfObscuration2 => "The Left Angle Cross of Obscuration 2",
                IncarnationCrosses.LeftAngleCrossOfPrevention => "The Left Angle Cross of Prevention",
                IncarnationCrosses.LeftAngleCrossOfPrevention2 => "The Left Angle Cross of Prevention 2",
                IncarnationCrosses.LeftAngleCrossOfRefinement2 => "The Left Angle Cross of Refinement 2",
                IncarnationCrosses.LeftAngleCrossOfRevolution => "The Left Angle Cross of Revolution",
                IncarnationCrosses.LeftAngleCrossOfRevolution2 => "The Left Angle Cross of Revolution 2",
                IncarnationCrosses.LeftAngleCrossOfSeparation => "The Left Angle Cross of Separation",
                IncarnationCrosses.LeftAngleCrossOfSeparation2 => "The Left Angle Cross of Separation 2",
                IncarnationCrosses.LeftAngleCrossOfSpirit => "The Left Angle Cross of Spirit",
                IncarnationCrosses.LeftAngleCrossOfSpirit2 => "The Left Angle Cross of Spirit 2",
                IncarnationCrosses.LeftAngleCrossOfUncertainty => "The Left Angle Cross of Uncertainty",
                IncarnationCrosses.LeftAngleCrossOfUncertainty2 => "The Left Angle Cross of Uncertainty 2",
                IncarnationCrosses.LeftAngleCrossOfUpheaval => "The Left Angle Cross of Upheaval",
                IncarnationCrosses.LeftAngleCrossOfUpheaval2 => "The Left Angle Cross of Upheaval 2",
                IncarnationCrosses.LeftAngleCrossOfWishes => "The Left Angle Cross of Wishes",
                IncarnationCrosses.LeftAngleCrossOfWishes2 => "The Left Angle Cross of Wishes 2",
                IncarnationCrosses.LeftAngleCrossOfTheAlpha => "The Left Angle Cross of the Alpha",
                IncarnationCrosses.LeftAngleCrossOfTheAlpha2 => "The Left Angle Cross of the Alpha 2",
                IncarnationCrosses.LeftAngleCrossOfTheClarion => "The Left Angle Cross of the Clarion",
                IncarnationCrosses.LeftAngleCrossOfTheClarion2 => "The Left Angle Cross of the Clarion 2",
                IncarnationCrosses.LeftAngleCrossOfThePlane2 => "The Left Angle Cross of the Plane 2",
                IncarnationCrosses.RightAngleCrossOfConsciousness => "The Right Angle Cross of Consciousness",
                IncarnationCrosses.RightAngleCrossOfConsciousness2 => "The Right Angle Cross of Consciousness 2",
                IncarnationCrosses.RightAngleCrossOfConsciousness3 => "The Right Angle Cross of Consciousness 3",
                IncarnationCrosses.RightAngleCrossOfConsciousness4 => "The Right Angle Cross of Consciousness 4",
                IncarnationCrosses.RightAngleCrossOfContagion => "The Right Angle Cross of Contagion",
                IncarnationCrosses.RightAngleCrossOfContagion2 => "The Right Angle Cross of Contagion 2",
                IncarnationCrosses.RightAngleCrossOfContagion3 => "The Right Angle Cross of Contagion 3",
                IncarnationCrosses.RightAngleCrossOfContagion4 => "The Right Angle Cross of Contagion 4",
                IncarnationCrosses.RightAngleCrossOfEden2 => "The Right Angle Cross of Eden 2",
                IncarnationCrosses.RightAngleCrossOfEden3 => "The Right Angle Cross of Eden 3",
                IncarnationCrosses.RightAngleCrossOfEden4 => "The Right Angle Cross of Eden 4",
                IncarnationCrosses.RightAngleCrossOfExplanation => "The Right Angle Cross of Explanation",
                IncarnationCrosses.RightAngleCrossOfExplanation2 => "The Right Angle Cross of Explanation 2",
                IncarnationCrosses.RightAngleCrossOfExplanation3 => "The Right Angle Cross of Explanation 3",
                IncarnationCrosses.RightAngleCrossOfExplanation4 => "The Right Angle Cross of Explanation 4",
                IncarnationCrosses.RightAngleCrossOfLaws => "The Right Angle Cross of Laws",
                IncarnationCrosses.RightAngleCrossOfLaws2 => "The Right Angle Cross of Laws 2",
                IncarnationCrosses.RightAngleCrossOfLaws3 => "The Right Angle Cross of Laws 3",
                IncarnationCrosses.RightAngleCrossOfLaws4 => "The Right Angle Cross of Laws 4",
                IncarnationCrosses.RightAngleCrossOfMaya => "The Right Angle Cross of Maya",
                IncarnationCrosses.RightAngleCrossOfMaya2 => "The Right Angle Cross of Maya 2",
                IncarnationCrosses.RightAngleCrossOfMaya3 => "The Right Angle Cross of Maya 3",
                IncarnationCrosses.RightAngleCrossOfMaya4 => "The Right Angle Cross of Maya 4",
                IncarnationCrosses.RightAngleCrossOfPenetration => "The Right Angle Cross of Penetration",
                IncarnationCrosses.RightAngleCrossOfPenetration2 => "The Right Angle Cross of Penetration 2",
                IncarnationCrosses.RightAngleCrossOfPenetration3 => "The Right Angle Cross of Penetration 3",
                IncarnationCrosses.RightAngleCrossOfPenetration4 => "The Right Angle Cross of Penetration 4",
                IncarnationCrosses.RightAngleCrossOfPlanning => "The Right Angle Cross of Planning",
                IncarnationCrosses.RightAngleCrossOfPlanning2 => "The Right Angle Cross of Planning 2",
                IncarnationCrosses.RightAngleCrossOfPlanning3 => "The Right Angle Cross of Planning 3",
                IncarnationCrosses.RightAngleCrossOfPlanning4 => "The Right Angle Cross of Planning 4",
                IncarnationCrosses.RightAngleCrossOfRulership => "The Right Angle Cross of Rulership",
                IncarnationCrosses.RightAngleCrossOfRulership2 => "The Right Angle Cross of Rulership 2",
                IncarnationCrosses.RightAngleCrossOfRulership3 => "The Right Angle Cross of Rulership 3",
                IncarnationCrosses.RightAngleCrossOfRulership4 => "The Right Angle Cross of Rulership 4",
                IncarnationCrosses.RightAngleCrossOfService => "The Right Angle Cross of Service",
                IncarnationCrosses.RightAngleCrossOfService2 => "The Right Angle Cross of Service 2",
                IncarnationCrosses.RightAngleCrossOfService3 => "The Right Angle Cross of Service 3",
                IncarnationCrosses.RightAngleCrossOfService4 => "The Right Angle Cross of Service 4",
                IncarnationCrosses.RightAngleCrossOfTension => "The Right Angle Cross of Tension",
                IncarnationCrosses.RightAngleCrossOfTension2 => "The Right Angle Cross of Tension 2",
                IncarnationCrosses.RightAngleCrossOfTension3 => "The Right Angle Cross of Tension 3",
                IncarnationCrosses.RightAngleCrossOfTension4 => "The Right Angle Cross of Tension 4",
                IncarnationCrosses.RightAngleCrossOfVesselOfLove4 => "The Right Angle Cross of Vessel of Love 4",
                IncarnationCrosses.RightAngleCrossOfTheEden => "The Right Angle Cross of the Eden",
                IncarnationCrosses.RightAngleCrossOfTheFourWays => "The Right Angle Cross of the Four Ways",
                IncarnationCrosses.RightAngleCrossOfTheFourWays2 => "The Right Angle Cross of the Four Ways 2",
                IncarnationCrosses.RightAngleCrossOfTheFourWays3 => "The Right Angle Cross of the Four Ways 3",
                IncarnationCrosses.RightAngleCrossOfTheFourWays4 => "The Right Angle Cross of the Four Ways 4",
                IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix => "The Right Angle Cross of the Sleeping Phoenix",
                IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix2 => "The Right Angle Cross of the Sleeping Phoenix 2",
                IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix3 => "The Right Angle Cross of the Sleeping Phoenix 3",
                IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix4 => "The Right Angle Cross of the Sleeping Phoenix 4",
                IncarnationCrosses.RightAngleCrossOfTheSphinx => "The Right Angle Cross of the Sphinx",
                IncarnationCrosses.RightAngleCrossOfTheSphinx2 => "The Right Angle Cross of the Sphinx 2",
                IncarnationCrosses.RightAngleCrossOfTheSphinx3 => "The Right Angle Cross of the Sphinx 3",
                IncarnationCrosses.RightAngleCrossOfTheSphinx4 => "The Right Angle Cross of the Sphinx 4",
                IncarnationCrosses.RightAngleCrossOfTheUnexpected => "The Right Angle Cross of the Unexpected",
                IncarnationCrosses.RightAngleCrossOfTheUnexpected2 => "The Right Angle Cross of the Unexpected 2",
                IncarnationCrosses.RightAngleCrossOfTheUnexpected3 => "The Right Angle Cross of the Unexpected 3",
                IncarnationCrosses.RightAngleCrossOfTheUnexpected4 => "The Right Angle Cross of the Unexpected 4",
                IncarnationCrosses.RightAngleCrossOfTheVesselOfLove => "The Right Angle Cross of the Vessel of Love",
                IncarnationCrosses.RightAngleCrossOfTheVesselOfLove2 => "The Right Angle Cross of the Vessel of Love 2",
                IncarnationCrosses.RightAngleCrossOfTheVesselOfLove3 => "The Right Angle Cross of the Vessel of Love 3"
            };
}