#pragma warning disable CS8524

namespace SharpAstrology.Enums;
public enum IncarnationCrosses
{
    JuxtapositionCrossOfAlertness,
    JuxtapositionCrossOfAmbition,
    JuxtapositionCrossOfArticulation,
    JuxtapositionCrossOfAssimilation,
    JuxtapositionCrossOfBargains,
    JuxtapositionCrossOfBeginnings,
    JuxtapositionCrossOfBehavior,
    JuxtapositionCrossOfCaring,
    JuxtapositionCrossOfCommitment,
    JuxtapositionCrossOfCompletion,
    JuxtapositionCrossOfConflict,
    JuxtapositionCrossOfConfusion,
    JuxtapositionCrossOfConservation,
    JuxtapositionCrossOfContribution,
    JuxtapositionCrossOfControl,
    JuxtapositionCrossOfCorrection,
    JuxtapositionCrossOfCrisis,
    JuxtapositionCrossOfDenial,
    JuxtapositionCrossOfDepth,
    JuxtapositionCrossOfDetail,
    JuxtapositionCrossOfDoubts,
    JuxtapositionCrossOfEmpowering,
    JuxtapositionCrossOfExperience,
    JuxtapositionCrossOfExperimentation,
    JuxtapositionCrossOfExtremes,
    JuxtapositionCrossOfFantasy,
    JuxtapositionCrossOfFates,
    JuxtapositionCrossOfFocus,
    JuxtapositionCrossOfFormulization,
    JuxtapositionCrossOfGrace,
    JuxtapositionCrossOfHabits,
    JuxtapositionCrossOfIdeas,
    JuxtapositionCrossOfInfluence,
    JuxtapositionCrossOfInnocence,
    JuxtapositionCrossOfInsight,
    JuxtapositionCrossOfInteraction,
    JuxtapositionCrossOfIntuition,
    JuxtapositionCrossOfLimitation,
    JuxtapositionCrossOfListening,
    JuxtapositionCrossOfMoods,
    JuxtapositionCrossOfMutation,
    JuxtapositionCrossOfNeed,
    JuxtapositionCrossOfOpinions,
    JuxtapositionCrossOfOpposition,
    JuxtapositionCrossOfOppression,
    JuxtapositionCrossOfPossession,
    JuxtapositionCrossOfPower,
    JuxtapositionCrossOfPrinciples,
    JuxtapositionCrossOfProvocation,
    JuxtapositionCrossOfRationalization,
    JuxtapositionCrossOfRetreat,
    JuxtapositionCrossOfRisks,
    JuxtapositionCrossOfSelfExpression,
    JuxtapositionCrossOfSerendipity,
    JuxtapositionCrossOfShock,
    JuxtapositionCrossOfStillness,
    JuxtapositionCrossOfStimulation,
    JuxtapositionCrossOfStrategy,
    JuxtapositionCrossOfThinking,
    JuxtapositionCrossOfValues,
    JuxtapositionCrossOfVitality,
    JuxtapositionCrossOfTheDriver,
    JuxtapositionCrossOfTheNow,
    JuxtapositionCrossOfTheTrickster,
    LeftAngleCrossOfDuality2,
    LeftAngleCrossOfIndividualism,
    LeftAngleCrossOfIndividualism2,
    LeftAngleCrossOfLimitation2,
    LeftAngleCrossOfRefinement,
    LeftAngleCrossOfThePlane,
    LeftAngleCrossOfAlignment,
    LeftAngleCrossOfAlignment2,
    LeftAngleCrossOfConfrontation,
    LeftAngleCrossOfConfrontation2,
    LeftAngleCrossOfCycles,
    LeftAngleCrossOfCycles2,
    LeftAngleCrossOfDedication,
    LeftAngleCrossOfDedication2,
    LeftAngleCrossOfDefiance,
    LeftAngleCrossOfDefiance2,
    LeftAngleCrossOfDemands,
    LeftAngleCrossOfDemands2,
    LeftAngleCrossOfDistraction,
    LeftAngleCrossOfDistraction2,
    LeftAngleCrossOfDominion,
    LeftAngleCrossOfDominion2,
    LeftAngleCrossOfDuality,
    LeftAngleCrossOfEducation,
    LeftAngleCrossOfEducation2,
    LeftAngleCrossOfEndeavour,
    LeftAngleCrossOfEndeavour2,
    LeftAngleCrossOfHealing,
    LeftAngleCrossOfHealing2,
    LeftAngleCrossOfIdentification,
    LeftAngleCrossOfIdentification2,
    LeftAngleCrossOfIncarnation,
    LeftAngleCrossOfIncarnation2,
    LeftAngleCrossOfIndustry,
    LeftAngleCrossOfIndustry2,
    LeftAngleCrossOfInforming,
    LeftAngleCrossOfInforming2,
    LeftAngleCrossOfLimitation,
    LeftAngleCrossOfMasks,
    LeftAngleCrossOfMasks2,
    LeftAngleCrossOfMigration,
    LeftAngleCrossOfMigration2,
    LeftAngleCrossOfObscuration,
    LeftAngleCrossOfObscuration2,
    LeftAngleCrossOfPrevention,
    LeftAngleCrossOfPrevention2,
    LeftAngleCrossOfRefinement2,
    LeftAngleCrossOfRevolution,
    LeftAngleCrossOfRevolution2,
    LeftAngleCrossOfSeparation,
    LeftAngleCrossOfSeparation2,
    LeftAngleCrossOfSpirit,
    LeftAngleCrossOfSpirit2,
    LeftAngleCrossOfUncertainty,
    LeftAngleCrossOfUncertainty2,
    LeftAngleCrossOfUpheaval,
    LeftAngleCrossOfUpheaval2,
    LeftAngleCrossOfWishes,
    LeftAngleCrossOfWishes2,
    LeftAngleCrossOfTheAlpha,
    LeftAngleCrossOfTheAlpha2,
    LeftAngleCrossOfTheClarion,
    LeftAngleCrossOfTheClarion2,
    LeftAngleCrossOfThePlane2,
    RightAngleCrossOfConsciousness,
    RightAngleCrossOfConsciousness2,
    RightAngleCrossOfConsciousness3,
    RightAngleCrossOfConsciousness4,
    RightAngleCrossOfContagion,
    RightAngleCrossOfContagion2,
    RightAngleCrossOfContagion3,
    RightAngleCrossOfContagion4,
    RightAngleCrossOfEden2,
    RightAngleCrossOfEden3,
    RightAngleCrossOfEden4,
    RightAngleCrossOfExplanation,
    RightAngleCrossOfExplanation2,
    RightAngleCrossOfExplanation3,
    RightAngleCrossOfExplanation4,
    RightAngleCrossOfLaws,
    RightAngleCrossOfLaws2,
    RightAngleCrossOfLaws3,
    RightAngleCrossOfLaws4,
    RightAngleCrossOfMaya,
    RightAngleCrossOfMaya2,
    RightAngleCrossOfMaya3,
    RightAngleCrossOfMaya4,
    RightAngleCrossOfPenetration,
    RightAngleCrossOfPenetration2,
    RightAngleCrossOfPenetration3,
    RightAngleCrossOfPenetration4,
    RightAngleCrossOfPlanning,
    RightAngleCrossOfPlanning2,
    RightAngleCrossOfPlanning3,
    RightAngleCrossOfPlanning4,
    RightAngleCrossOfRulership,
    RightAngleCrossOfRulership2,
    RightAngleCrossOfRulership3,
    RightAngleCrossOfRulership4,
    RightAngleCrossOfService,
    RightAngleCrossOfService2,
    RightAngleCrossOfService3,
    RightAngleCrossOfService4,
    RightAngleCrossOfTension,
    RightAngleCrossOfTension2,
    RightAngleCrossOfTension3,
    RightAngleCrossOfTension4,
    RightAngleCrossOfVesselOfLove4,
    RightAngleCrossOfTheEden,
    RightAngleCrossOfTheFourWays,
    RightAngleCrossOfTheFourWays2,
    RightAngleCrossOfTheFourWays3,
    RightAngleCrossOfTheFourWays4,
    RightAngleCrossOfTheSleepingPhoenix,
    RightAngleCrossOfTheSleepingPhoenix2,
    RightAngleCrossOfTheSleepingPhoenix3,
    RightAngleCrossOfTheSleepingPhoenix4,
    RightAngleCrossOfTheSphinx,
    RightAngleCrossOfTheSphinx2,
    RightAngleCrossOfTheSphinx3,
    RightAngleCrossOfTheSphinx4,
    RightAngleCrossOfTheUnexpected,
    RightAngleCrossOfTheUnexpected2,
    RightAngleCrossOfTheUnexpected3,
    RightAngleCrossOfTheUnexpected4,
    RightAngleCrossOfTheVesselOfLove,
    RightAngleCrossOfTheVesselOfLove2,
    RightAngleCrossOfTheVesselOfLove3
}
public static class IncarnationCrossesExtensionMethods
{
    public static (Gates, Angles) ToGeneKeys(this IncarnationCrosses cross) => cross switch
    {
        IncarnationCrosses.JuxtapositionCrossOfAlertness => (Gates.Key44, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfAmbition => (Gates.Key54, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfArticulation => (Gates.Key12, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfAssimilation => (Gates.Key23, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfBargains => (Gates.Key37, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfBeginnings => (Gates.Key53, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfBehavior => (Gates.Key10, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCaring => (Gates.Key27, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCommitment => (Gates.Key29, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCompletion => (Gates.Key42, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfConflict => (Gates.Key6, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfConfusion => (Gates.Key64, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfConservation => (Gates.Key32, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfContribution => (Gates.Key8, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfControl => (Gates.Key21, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCorrection => (Gates.Key18, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfCrisis => (Gates.Key36, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDenial => (Gates.Key40, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDepth => (Gates.Key48, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDetail => (Gates.Key62, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfDoubts => (Gates.Key63, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfEmpowering => (Gates.Key14, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfExperience => (Gates.Key35, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfExperimentation => (Gates.Key16, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfExtremes => (Gates.Key15, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFantasy => (Gates.Key41, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFates => (Gates.Key30, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFocus => (Gates.Key9, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfFormulization => (Gates.Key4, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfGrace => (Gates.Key22, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfHabits => (Gates.Key5, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfIdeas => (Gates.Key11, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInfluence => (Gates.Key31, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInnocence => (Gates.Key25, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInsight => (Gates.Key43, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfInteraction => (Gates.Key7, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfIntuition => (Gates.Key57, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfLimitation => (Gates.Key60, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfListening => (Gates.Key13, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfMoods => (Gates.Key55, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfMutation => (Gates.Key3, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfNeed => (Gates.Key19, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfOpinions => (Gates.Key17, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfOpposition => (Gates.Key38, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfOppression => (Gates.Key47, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfPossession => (Gates.Key45, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfPower => (Gates.Key34, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfPrinciples => (Gates.Key49, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfProvocation => (Gates.Key39, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfRationalization => (Gates.Key24, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfRetreat => (Gates.Key33, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfRisks => (Gates.Key28, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfSelfExpression => (Gates.Key1, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfSerendipity => (Gates.Key46, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfShock => (Gates.Key51, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfStillness => (Gates.Key52, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfStimulation => (Gates.Key56, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfStrategy => (Gates.Key59, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfThinking => (Gates.Key61, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfValues => (Gates.Key50, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfVitality => (Gates.Key58, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfTheDriver => (Gates.Key2, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfTheNow => (Gates.Key20, Angles.Juxtaposition),
        IncarnationCrosses.JuxtapositionCrossOfTheTrickster => (Gates.Key26, Angles.Juxtaposition),
        IncarnationCrosses.LeftAngleCrossOfDuality2 => (Gates.Key34, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndividualism => (Gates.Key39, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndividualism2 => (Gates.Key38, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfLimitation2 => (Gates.Key32, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRefinement => (Gates.Key33, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfThePlane => (Gates.Key36, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfAlignment => (Gates.Key27, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfAlignment2 => (Gates.Key28, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfConfrontation => (Gates.Key45, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfConfrontation2 => (Gates.Key26, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfCycles => (Gates.Key53, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfCycles2 => (Gates.Key54, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDedication => (Gates.Key23, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDedication2 => (Gates.Key43, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDefiance => (Gates.Key2, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDefiance2 => (Gates.Key1, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDemands => (Gates.Key52, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDemands2 => (Gates.Key58, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDistraction => (Gates.Key56, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDistraction2 => (Gates.Key60, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDominion => (Gates.Key63, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDominion2 => (Gates.Key64, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfDuality => (Gates.Key20, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEducation => (Gates.Key12, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEducation2 => (Gates.Key11, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEndeavour => (Gates.Key21, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfEndeavour2 => (Gates.Key48, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfHealing => (Gates.Key25, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfHealing2 => (Gates.Key46, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIdentification => (Gates.Key16, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIdentification2 => (Gates.Key9, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIncarnation => (Gates.Key24, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIncarnation2 => (Gates.Key44, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndustry => (Gates.Key30, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfIndustry2 => (Gates.Key29, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfInforming => (Gates.Key22, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfInforming2 => (Gates.Key47, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfLimitation => (Gates.Key42, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMasks => (Gates.Key13, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMasks2 => (Gates.Key7, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMigration => (Gates.Key37, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfMigration2 => (Gates.Key40, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfObscuration => (Gates.Key62, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfObscuration2 => (Gates.Key61, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfPrevention => (Gates.Key15, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfPrevention2 => (Gates.Key10, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRefinement2 => (Gates.Key19, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRevolution => (Gates.Key49, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfRevolution2 => (Gates.Key4, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSeparation => (Gates.Key35, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSeparation2 => (Gates.Key5, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSpirit => (Gates.Key55, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfSpirit2 => (Gates.Key59, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUncertainty => (Gates.Key8, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUncertainty2 => (Gates.Key14, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUpheaval => (Gates.Key17, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfUpheaval2 => (Gates.Key18, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfWishes => (Gates.Key3, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfWishes2 => (Gates.Key50, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheAlpha => (Gates.Key31, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheAlpha2 => (Gates.Key41, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheClarion => (Gates.Key51, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfTheClarion2 => (Gates.Key57, Angles.Left),
        IncarnationCrosses.LeftAngleCrossOfThePlane2 => (Gates.Key6, Angles.Left),
        IncarnationCrosses.RightAngleCrossOfConsciousness => (Gates.Key63, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfConsciousness2 => (Gates.Key35, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfConsciousness3 => (Gates.Key64, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfConsciousness4 => (Gates.Key5, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion => (Gates.Key30, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion2 => (Gates.Key8, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion3 => (Gates.Key29, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfContagion4 => (Gates.Key14, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfEden2 => (Gates.Key12, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfEden3 => (Gates.Key6, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfEden4 => (Gates.Key11, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation => (Gates.Key49, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation2 => (Gates.Key23, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation3 => (Gates.Key4, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfExplanation4 => (Gates.Key43, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws => (Gates.Key3, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws2 => (Gates.Key56, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws3 => (Gates.Key50, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfLaws4 => (Gates.Key60, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya => (Gates.Key42, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya2 => (Gates.Key62, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya3 => (Gates.Key32, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfMaya4 => (Gates.Key61, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration => (Gates.Key51, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration2 => (Gates.Key53, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration3 => (Gates.Key57, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPenetration4 => (Gates.Key54, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning => (Gates.Key37, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning2 => (Gates.Key16, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning3 => (Gates.Key40, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfPlanning4 => (Gates.Key9, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership => (Gates.Key22, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership2 => (Gates.Key45, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership3 => (Gates.Key47, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfRulership4 => (Gates.Key26, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService => (Gates.Key17, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService2 => (Gates.Key52, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService3 => (Gates.Key18, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfService4 => (Gates.Key58, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension => (Gates.Key21, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension2 => (Gates.Key39, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension3 => (Gates.Key48, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTension4 => (Gates.Key38, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfVesselOfLove4 => (Gates.Key10, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheEden => (Gates.Key36, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays => (Gates.Key24, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays2 => (Gates.Key33, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays3 => (Gates.Key44, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheFourWays4 => (Gates.Key19, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix => (Gates.Key55, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix2 => (Gates.Key20, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix3 => (Gates.Key59, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix4 => (Gates.Key34, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx => (Gates.Key13, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx2 => (Gates.Key2, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx3 => (Gates.Key7, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheSphinx4 => (Gates.Key1, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected => (Gates.Key27, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected2 => (Gates.Key31, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected3 => (Gates.Key28, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheUnexpected4 => (Gates.Key41, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheVesselOfLove => (Gates.Key25, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheVesselOfLove2 => (Gates.Key15, Angles.Right),
        IncarnationCrosses.RightAngleCrossOfTheVesselOfLove3 => (Gates.Key46, Angles.Right)
    };

        public static IncarnationCrosses ToIncarnationCross(this (Gates, Angles) position) => position switch
            {
                (Gates.Key44, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfAlertness,
                (Gates.Key54, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfAmbition,
                (Gates.Key12, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfArticulation,
                (Gates.Key23, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfAssimilation,
                (Gates.Key37, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfBargains,
                (Gates.Key53, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfBeginnings,
                (Gates.Key10, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfBehavior,
                (Gates.Key27, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCaring,
                (Gates.Key29, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCommitment,
                (Gates.Key42, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCompletion,
                (Gates.Key6, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfConflict,
                (Gates.Key64, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfConfusion,
                (Gates.Key32, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfConservation,
                (Gates.Key8, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfContribution,
                (Gates.Key21, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfControl,
                (Gates.Key18, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCorrection,
                (Gates.Key36, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfCrisis,
                (Gates.Key40, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDenial,
                (Gates.Key48, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDepth,
                (Gates.Key62, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDetail,
                (Gates.Key63, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfDoubts,
                (Gates.Key14, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfEmpowering,
                (Gates.Key35, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfExperience,
                (Gates.Key16, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfExperimentation,
                (Gates.Key15, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfExtremes,
                (Gates.Key41, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFantasy,
                (Gates.Key30, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFates,
                (Gates.Key9, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFocus,
                (Gates.Key4, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfFormulization,
                (Gates.Key22, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfGrace,
                (Gates.Key5, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfHabits,
                (Gates.Key11, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfIdeas,
                (Gates.Key31, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInfluence,
                (Gates.Key25, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInnocence,
                (Gates.Key43, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInsight,
                (Gates.Key7, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfInteraction,
                (Gates.Key57, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfIntuition,
                (Gates.Key60, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfLimitation,
                (Gates.Key13, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfListening,
                (Gates.Key55, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfMoods,
                (Gates.Key3, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfMutation,
                (Gates.Key19, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfNeed,
                (Gates.Key17, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfOpinions,
                (Gates.Key38, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfOpposition,
                (Gates.Key47, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfOppression,
                (Gates.Key45, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfPossession,
                (Gates.Key34, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfPower,
                (Gates.Key49, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfPrinciples,
                (Gates.Key39, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfProvocation,
                (Gates.Key24, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfRationalization,
                (Gates.Key33, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfRetreat,
                (Gates.Key28, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfRisks,
                (Gates.Key1, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfSelfExpression,
                (Gates.Key46, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfSerendipity,
                (Gates.Key51, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfShock,
                (Gates.Key52, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfStillness,
                (Gates.Key56, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfStimulation,
                (Gates.Key59, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfStrategy,
                (Gates.Key61, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfThinking,
                (Gates.Key50, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfValues,
                (Gates.Key58, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfVitality,
                (Gates.Key2, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfTheDriver,
                (Gates.Key20, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfTheNow,
                (Gates.Key26, Angles.Juxtaposition) => IncarnationCrosses.JuxtapositionCrossOfTheTrickster,
                (Gates.Key34, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDuality2,
                (Gates.Key39, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndividualism,
                (Gates.Key38, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndividualism2,
                (Gates.Key32, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfLimitation2,
                (Gates.Key33, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRefinement,
                (Gates.Key36, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfThePlane,
                (Gates.Key27, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfAlignment,
                (Gates.Key28, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfAlignment2,
                (Gates.Key45, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfConfrontation,
                (Gates.Key26, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfConfrontation2,
                (Gates.Key53, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfCycles,
                (Gates.Key54, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfCycles2,
                (Gates.Key23, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDedication,
                (Gates.Key43, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDedication2,
                (Gates.Key2, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDefiance,
                (Gates.Key1, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDefiance2,
                (Gates.Key52, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDemands,
                (Gates.Key58, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDemands2,
                (Gates.Key56, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDistraction,
                (Gates.Key60, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDistraction2,
                (Gates.Key63, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDominion,
                (Gates.Key64, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDominion2,
                (Gates.Key20, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfDuality,
                (Gates.Key12, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEducation,
                (Gates.Key11, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEducation2,
                (Gates.Key21, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEndeavour,
                (Gates.Key48, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfEndeavour2,
                (Gates.Key25, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfHealing,
                (Gates.Key46, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfHealing2,
                (Gates.Key16, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIdentification,
                (Gates.Key9, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIdentification2,
                (Gates.Key24, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIncarnation,
                (Gates.Key44, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIncarnation2,
                (Gates.Key30, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndustry,
                (Gates.Key29, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfIndustry2,
                (Gates.Key22, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfInforming,
                (Gates.Key47, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfInforming2,
                (Gates.Key42, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfLimitation,
                (Gates.Key13, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMasks,
                (Gates.Key7, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMasks2,
                (Gates.Key37, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMigration,
                (Gates.Key40, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfMigration2,
                (Gates.Key62, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfObscuration,
                (Gates.Key61, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfObscuration2,
                (Gates.Key15, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfPrevention,
                (Gates.Key10, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfPrevention2,
                (Gates.Key19, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRefinement2,
                (Gates.Key49, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRevolution,
                (Gates.Key4, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfRevolution2,
                (Gates.Key35, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSeparation,
                (Gates.Key5, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSeparation2,
                (Gates.Key55, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSpirit,
                (Gates.Key59, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfSpirit2,
                (Gates.Key8, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUncertainty,
                (Gates.Key14, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUncertainty2,
                (Gates.Key17, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUpheaval,
                (Gates.Key18, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfUpheaval2,
                (Gates.Key3, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfWishes,
                (Gates.Key50, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfWishes2,
                (Gates.Key31, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheAlpha,
                (Gates.Key41, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheAlpha2,
                (Gates.Key51, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheClarion,
                (Gates.Key57, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfTheClarion2,
                (Gates.Key6, Angles.Left) => IncarnationCrosses.LeftAngleCrossOfThePlane2,
                (Gates.Key63, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness,
                (Gates.Key35, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness2,
                (Gates.Key64, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness3,
                (Gates.Key5, Angles.Right) => IncarnationCrosses.RightAngleCrossOfConsciousness4,
                (Gates.Key30, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion,
                (Gates.Key8, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion2,
                (Gates.Key29, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion3,
                (Gates.Key14, Angles.Right) => IncarnationCrosses.RightAngleCrossOfContagion4,
                (Gates.Key12, Angles.Right) => IncarnationCrosses.RightAngleCrossOfEden2,
                (Gates.Key6, Angles.Right) => IncarnationCrosses.RightAngleCrossOfEden3,
                (Gates.Key11, Angles.Right) => IncarnationCrosses.RightAngleCrossOfEden4,
                (Gates.Key49, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation,
                (Gates.Key23, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation2,
                (Gates.Key4, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation3,
                (Gates.Key43, Angles.Right) => IncarnationCrosses.RightAngleCrossOfExplanation4,
                (Gates.Key3, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws,
                (Gates.Key56, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws2,
                (Gates.Key50, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws3,
                (Gates.Key60, Angles.Right) => IncarnationCrosses.RightAngleCrossOfLaws4,
                (Gates.Key42, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya,
                (Gates.Key62, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya2,
                (Gates.Key32, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya3,
                (Gates.Key61, Angles.Right) => IncarnationCrosses.RightAngleCrossOfMaya4,
                (Gates.Key51, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration,
                (Gates.Key53, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration2,
                (Gates.Key57, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration3,
                (Gates.Key54, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPenetration4,
                (Gates.Key37, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning,
                (Gates.Key16, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning2,
                (Gates.Key40, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning3,
                (Gates.Key9, Angles.Right) => IncarnationCrosses.RightAngleCrossOfPlanning4,
                (Gates.Key22, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership,
                (Gates.Key45, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership2,
                (Gates.Key47, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership3,
                (Gates.Key26, Angles.Right) => IncarnationCrosses.RightAngleCrossOfRulership4,
                (Gates.Key17, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService,
                (Gates.Key52, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService2,
                (Gates.Key18, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService3,
                (Gates.Key58, Angles.Right) => IncarnationCrosses.RightAngleCrossOfService4,
                (Gates.Key21, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension,
                (Gates.Key39, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension2,
                (Gates.Key48, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension3,
                (Gates.Key38, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTension4,
                (Gates.Key10, Angles.Right) => IncarnationCrosses.RightAngleCrossOfVesselOfLove4,
                (Gates.Key36, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheEden,
                (Gates.Key24, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays,
                (Gates.Key33, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays2,
                (Gates.Key44, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays3,
                (Gates.Key19, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheFourWays4,
                (Gates.Key55, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix,
                (Gates.Key20, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix2,
                (Gates.Key59, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix3,
                (Gates.Key34, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSleepingPhoenix4,
                (Gates.Key13, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx,
                (Gates.Key2, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx2,
                (Gates.Key7, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx3,
                (Gates.Key1, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheSphinx4,
                (Gates.Key27, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected,
                (Gates.Key31, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected2,
                (Gates.Key28, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected3,
                (Gates.Key41, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheUnexpected4,
                (Gates.Key25, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheVesselOfLove,
                (Gates.Key15, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheVesselOfLove2,
                (Gates.Key46, Angles.Right) => IncarnationCrosses.RightAngleCrossOfTheVesselOfLove3
            };
    }